version: '3.8'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - database_folder:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=Postgres
      - POSTGRES_PASSWORD=DevPassword

volumes:
  database_folder:
