databases:
  - name: photo_db
    ipAllowList: []
    databaseName: photoalbum_production
    region: frankfurt
    plan: free

services:
  - type: redis
    name: redis
    ipAllowList: [ ] # only allow internal connections
    plan: free # optional (defaults to starter)
    region: frankfurt
    maxmemoryPolicy: allkeys-lfu # optional (defaults to allkeys-lru). Rails recommends allkeys-lfu as a default.
  - type: web
    runtime: docker
    name: photo_album
    repo: https://github.com/bbucsy/BMEVIIIMB12-homework-bbucsy
    plan: starter # Connecting to redis on Private network does not work with free instance
    region: frankfurt
    autoDeploy: true
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: REDIS_URL # this must match the name of the environment variable used in production.rb
        fromService:
          type: redis
          name: redis
          property: connectionString
      - key: DATABASE_URL
        fromDatabase:
          name: photo_db
          property: connectionString
      - key: WEB_CONCURRENCY
        value: 2