services:
  - type: web
    runtime: docker
    name: photo_album
    repo: https://github.com/bbucsy/BMEVIIIMB12-homework-bbucsy
    plan: free
    region: frankfurt
    autoDeploy: true
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false